development:
  store: https://test1-239283829347123859138727.myshopify.com/
  password: shptka_1396418b4b48c0c11e8643d9cf6ea573
  theme_id: "151521525912"
  ignore_files:
    - config/settings_data.json
    - "*.log"

production:
  store: https://test1-239283829347123859138727.myshopify.com/
  password: shptka_1396418b4b48c0c11e8643d9cf6ea573
  theme_id: "151521525912"
